name: ğŸ–¥ï¸ i9 Tech CD - Entrega ContÃ­nua (Docker Build + Push)

on:
  push:
    branches: [develop, main]

jobs:
  build-and-push:
    name: ğŸ³ Build e PublicaÃ§Ã£o da Imagem Docker
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: ğŸ” Checkout do cÃ³digo
        uses: actions/checkout@v4

      - name: ğŸ” Login no Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN}}

      - name: ğŸ·ï¸ Extrair metadados (Tags/Labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_IMAGE_NAME }}
          tags: |
            type=sha
            type=ref,event=branch
            latest

      - name: ğŸš€ Build e Push da imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}